# Generated by Django 5.1.5 on 2025-10-08 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Legislator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the legislator", max_length=200
                    ),
                ),
            ],
            options={
                "db_table": "legislative_legislator",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the bill", max_length=500),
                ),
                (
                    "primary_sponsor",
                    models.ForeignKey(
                        help_text="Primary sponsor of this bill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsored_bills",
                        to="legislative.legislator",
                    ),
                ),
            ],
            options={
                "db_table": "legislative_bill",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        help_text="Bill being voted on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="legislative.bill",
                    ),
                ),
            ],
            options={
                "db_table": "legislative_vote",
            },
        ),
        migrations.CreateModel(
            name="VoteResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("1", "Yea"), ("2", "Nay")],
                        help_text="Vote type: Yea (support) or Nay (oppose)",
                        max_length=1,
                    ),
                ),
                (
                    "legislator",
                    models.ForeignKey(
                        help_text="Legislator who cast this vote",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_results",
                        to="legislative.legislator",
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        help_text="Vote session this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="legislative.vote",
                    ),
                ),
            ],
            options={
                "db_table": "legislative_vote_result",
                "indexes": [
                    models.Index(
                        fields=["vote_type"], name="legislative_vote_ty_59ef70_idx"
                    ),
                    models.Index(
                        fields=["vote", "vote_type"],
                        name="legislative_vote_id_e9be49_idx",
                    ),
                    models.Index(
                        fields=["legislator", "vote_type"],
                        name="legislative_legisla_16fec0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legislator", "vote"), name="unique_legislator_vote"
                    )
                ],
            },
        ),
    ]
